package protectbuild

import (
	"crypto/ed25519"
	"crypto/rand"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"go/format"
	"io"
	"os"
	"path/filepath"
	"strconv"
	"strings"

	"github.com/umbraforge/desktop/internal/protectedbundle"
)

type Options struct {
	Root         string
	ManifestPath string
	BundleOut    string
	ConfigOut    string
	BuildID      string
	MasterKey    []byte
	SigningKey   ed25519.PrivateKey
	Random       io.Reader
}

type Result struct {
	Info      protectedbundle.Info
	MasterKey []byte
	PublicKey ed25519.PublicKey
}

type manifestFile struct {
	Files []string `json:"files"`
}

// Build creates a uniquely keyed encrypted plugin bundle and a Go source file
// that pairs only that bundle with a protected executable. ConfigOut is a
// temporary build input and must be deleted by the release script afterwards.
func Build(opts Options) (Result, error) {
	if strings.TrimSpace(opts.Root) == "" || strings.TrimSpace(opts.ManifestPath) == "" || strings.TrimSpace(opts.BundleOut) == "" || strings.TrimSpace(opts.ConfigOut) == "" {
		return Result{}, errors.New("root, manifest, bundle output and config output are required")
	}
	rng := opts.Random
	if rng == nil {
		rng = rand.Reader
	}
	manifestRaw, err := os.ReadFile(opts.ManifestPath)
	if err != nil {
		return Result{}, err
	}
	var manifest manifestFile
	if err := json.Unmarshal(manifestRaw, &manifest); err != nil {
		return Result{}, fmt.Errorf("decode protection manifest: %w", err)
	}
	if len(manifest.Files) == 0 {
		return Result{}, errors.New("protection manifest contains no files")
	}

	master := append([]byte(nil), opts.MasterKey...)
	if len(master) == 0 {
		master = make([]byte, 32)
		if _, err := io.ReadFull(rng, master); err != nil {
			return Result{}, err
		}
	}
	if len(master) != 32 {
		return Result{}, fmt.Errorf("master key must be 32 bytes, got %d", len(master))
	}
	priv := append(ed25519.PrivateKey(nil), opts.SigningKey...)
	var pub ed25519.PublicKey
	if len(priv) == 0 {
		generatedPub, generatedPriv, err := ed25519.GenerateKey(rng)
		if err != nil {
			return Result{}, err
		}
		pub, priv = generatedPub, generatedPriv
	} else {
		if len(priv) != ed25519.PrivateKeySize {
			return Result{}, fmt.Errorf("signing key must be %d bytes", ed25519.PrivateKeySize)
		}
		pub = append(ed25519.PublicKey(nil), priv.Public().(ed25519.PublicKey)...)
	}
	buildID := strings.TrimSpace(opts.BuildID)
	if buildID == "" {
		var raw [16]byte
		if _, err := io.ReadFull(rng, raw[:]); err != nil {
			return Result{}, err
		}
		buildID = hex.EncodeToString(raw[:])
	}

	info, err := protectedbundle.Pack(opts.BundleOut, protectedbundle.PackOptions{
		Root:       opts.Root,
		BuildID:    buildID,
		MasterKey:  master,
		SigningKey: priv,
		Paths:      manifest.Files,
	})
	if err != nil {
		return Result{}, err
	}
	shareA := make([]byte, 32)
	if _, err := io.ReadFull(rng, shareA); err != nil {
		return Result{}, err
	}
	shareB := make([]byte, 32)
	for i := range shareB {
		shareB[i] = shareA[i] ^ master[i]
	}
	configSource := fmt.Sprintf(`// Code generated by ufpack; DO NOT EDIT.
//go:build protected

package protectionconfig

import "crypto/ed25519"

const (
	protectedBuildID = %s
)

var (
	protectedKeyShareA = []byte{%s}
	protectedKeyShareB = []byte{%s}
	protectedPublicKey = []byte{%s}
)

func Enabled() bool { return true }
func BuildID() string { return protectedBuildID }
func Credentials() ([]byte, ed25519.PublicKey, error) {
	return combineCredentials(protectedKeyShareA, protectedKeyShareB, protectedPublicKey)
}
`,
		strconv.Quote(buildID),
		goByteList(shareA),
		goByteList(shareB),
		goByteList(pub),
	)
	formatted, err := format.Source([]byte(configSource))
	if err != nil {
		return Result{}, fmt.Errorf("format generated protection config: %w", err)
	}
	if err := atomicWrite(opts.ConfigOut, formatted, 0o600); err != nil {
		return Result{}, err
	}
	return Result{Info: info, MasterKey: master, PublicKey: pub}, nil
}

func goByteList(b []byte) string {
	parts := make([]string, len(b))
	for i, v := range b {
		parts[i] = fmt.Sprintf("0x%02x", v)
	}
	return strings.Join(parts, ", ")
}

func atomicWrite(path string, body []byte, mode os.FileMode) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o700); err != nil {
		return err
	}
	tmp, err := os.CreateTemp(filepath.Dir(path), ".ufpack-")
	if err != nil {
		return err
	}
	name := tmp.Name()
	defer os.Remove(name)
	if err := tmp.Chmod(mode); err != nil {
		_ = tmp.Close()
		return err
	}
	if _, err := tmp.Write(body); err != nil {
		_ = tmp.Close()
		return err
	}
	if err := tmp.Close(); err != nil {
		return err
	}
	_ = os.Remove(path)
	return os.Rename(name, path)
}
